---
- name: Install Vim (Requires root)
  become: true
  ansible.builtin.package:
    name: vim
    state: present

- name: Copy the .vimrc file to the user's home directory
  become: false
  ansible.builtin.copy:
    src: files/.vimrc
    dest: "/home/{{ ansible_user }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    backup: yes
